name: daily-rebuild

on:
  schedule:
    - cron: '30 8 * * *'
  push:
  workflow_dispatch:

jobs:
  everything:
    runs-on: ubuntu-latest
    steps:
      - uses: jurassiscripts/setup-velociraptor@v2
        with:
          checkout: false

      - name: Clone the generator (this repo)
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.github_token }}
          path: generator
          persist-credentials: false
          fetch-depth: 0

      - name: Install FFmpeg
        run: sudo apt-get install ffmpeg

      - name: Build the spec
        run: cd generator && vr build

      - name: Clone the fork
        uses: actions/checkout@v2
        with:
          repository: 'ryanccn-bot/autocomplete'
          token: ${{ secrets.bot_token }}
          persist-credentials: false
          fetch-depth: 0

      - name: Copy the file
        run: cp generator/ffmpeg.ts src/ffmpeg.ts

      - name: Delete the generator
        run: rm -rf generator/

      - name: npm run lint:fix
        run: npm i && npm run lint:fix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.bot_token }}
          commit-message: 'chore(ffmpeg): automated update'
          committer: ryanccn-bot <98804099+ryanccn-bot@users.noreply.github.com>
          author: ryanccn-bot <98804099+ryanccn-bot@users.noreply.github.com>
          branch: ffmpeg-autoupdate
          title: 'automated update of `ffmpeg`'
