name: daily-rebuild

on:
  schedule:
    - cron: "30 8 * * *"
  push:

jobs:
  everything:
    runs-on: ubuntu-latest
    steps:
      - uses: jurassiscripts/setup-velociraptor@v2

      - name: Install FFmpeg
        run: sudo apt-get install ffmpeg

      - name: Build the spec
        run: vr build

      - name: Open a PR (if necessary)
        run: vr update-upstream
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
