name: daily-rebuild

on:
  schedule:
    - cron: '30 8 * * *'
  push:
  workflow_dispatch:

jobs:
  everything:
    runs-on: ubuntu-latest
    steps:
      - uses: jurassiscripts/setup-velociraptor@v2

      - name: Install FFmpeg
        run: sudo apt-get install ffmpeg

      - name: Build the spec
        run: vr build

      - name: Clone the fork
        uses: actions/checkout@v2
        with:
          repository: 'ryanccn-bot/autocomplete'
          token: ${{ secrets.bot_token }}
          path: fig-fork
          persist-credentials: false
          fetch-depth: 0

      - name: Copy the file
        run: cp ffmpeg.ts fig-fork/src/ffmpeg.ts

      - name: Run lint:fix
        run: cd fig-fork && npm i && npm run lint:fix

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.bot_token }}
          author_email: '98804099+ryanccn-bot@users.noreply.github.com'
          author_name: 'ryanccn-bot'
          directory: 'fig-fork'
          repository: 'ryanccn-bot/autocomplete'
          branch: 'ffmpeg-autoupdate'
